// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dbgen

import (
	"database/sql"
	"time"
)

type Answer struct {
	QuizID    string    `json:"quiz_id"`
	UserID    string    `json:"user_id"`
	AnswerNum int16     `json:"answer_num"`
	CreatedAt time.Time `json:"created_at"`
}

type Quiz struct {
	ID          string         `json:"id"`
	UserID      string         `json:"user_id"`
	Content     string         `json:"content"`
	Option1     string         `json:"option_1"`
	Option2     string         `json:"option_2"`
	Option3     sql.NullString `json:"option_3"`
	Option4     sql.NullString `json:"option_4"`
	CorrectNum  int16          `json:"correct_num"`
	Explanation sql.NullString `json:"explanation"`
	CreatedAt   time.Time      `json:"created_at"`
}

type User struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	AvatarUrl string    `json:"avatar_url"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
