services:
  db:
    image: mysql:9.0.1
    platform: linux/amd64
    container_name: mysql
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    restart: always

  server:
    build: .
    tty: true
    container_name: server
    ports:
      - "8080:8080"
    environment:
      SERVER_ADDRESS: 0.0.0.0
      SERVER_PORT: 8080
      GRACEFUL_SHUTDOWN_TIMEOUT: 0
      DB_DATABASE: db
      DB_USER: user
      DB_PASS: password
      DB_PORT: 3306
      DB_HOST: mysql
    depends_on:
      - db

volumes:
  db_data:
