// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dbgen

import (
	"context"
)

type Querier interface {
	DeleteQuiz(ctx context.Context, id string) error
	DeleteUser(ctx context.Context, id string) error
	FindLatestQuizzes(ctx context.Context, arg FindLatestQuizzesParams) ([]Quiz, error)
	FindQuizByID(ctx context.Context, id string) (Quiz, error)
	FindQuizzesByUserID(ctx context.Context, arg FindQuizzesByUserIDParams) ([]Quiz, error)
	InsertQuiz(ctx context.Context, arg InsertQuizParams) error
	InsertUser(ctx context.Context, arg InsertUserParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UserFindAll(ctx context.Context) ([]User, error)
	UserFindByID(ctx context.Context, id string) (User, error)
}

var _ Querier = (*Queries)(nil)
